[project]
name = "mvideo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alibabacloud-oss-v2>=1.0.0",
    "click>=8.3.1",
    "dashscope>=1.20.0",
    "loguru>=0.7.3",
    "rich>=14.2.0",
    "typer>=0.21.1",
]
